###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

# docker-comporse build -- rebuild

myapp-mysql:
  image: mysql:5.7
  container_name: myapp-mysql
  hostname: myapp-mysql
  volumes:
    - ../mysql:/var/lib/mysql
    - ./mysql/my.cnf:/etc/mysql/my.cnf
    - ../sql:/home/sql
  ports:
    - '8106:3306'
  environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  command: '--innodb_use_native_aio=0'

myapp-nginx:
  image: nginx:latest
  container_name: myapp-nginx
  volumes:
    - ../../home-care/cakephp:/var/www/myapp
    - ../../html:/var/www/html
    - ./logs:/var/www/logs
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
    - '8180:80'
  links:
    - myapp-php-fpm

# myapp-httpd:
#   image: httpd:latest
#   container_name: myapp-httpd
#   volumes:
#     - ../../home-care/cakephp:/var/www/myapp
#     - ../../html:/var/www/html
#     - ./logs:/var/www/logs
#     - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf

#   ports:
#     - '8180:80'
#   links:
#     - myapp-php-fpm

myapp-php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: myapp-php-fpm
  volumes:
    - ../../home-care/cakephp:/var/www/myapp
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
  links:
    - myapp-mysql
    # - myapp-mailhog

myapp-phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
    - 8080:80
  environment:
    - PMA_HOST=myapp-mysql
    - MAX_EXECUTION_TIME=86400
    - UPLOAD_LIMIT=100M
    # - PMA_CONFIG_BASE64=PD9waHAKJGNmZ1snTG9naW5Db29raWVWYWxpZGl0eSddID0gMzYwMCAqIDI0ICogMzY1Ow==
  links:
    - myapp-mysql
  volumes:
    - ./phpmyadmin/config.inc.php:/var/www/html/config.inc.php

# myapp-mailhog:
#   image: mailhog/mailhog:latest
#   container_name: myapp-mailhog
#   ports:
#     - "8125:8025"