###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

# docker-compose build -- rebuild
# docker-compose --env-file .env.homecare up -d
version: '3'
services:
  myapp-nginx:
    image: nginx:latest
    container_name: myapp-nginx
    volumes:
      - ../${CAKEPHP}:/var/www/myapp
      - ../html:/var/www/html
      - ./logs:/var/www/logs
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '7000:80'
    depends_on:
      - myapp-php-fpm

  myapp2-nginx:
    image: nginx:latest
    container_name: myapp2-nginx
    volumes:
      - ../${CAKEPHP2}:/var/www/myapp2
      - ../html:/var/www/html
      - ./logs:/var/www/logs
      - ./nginx/nginx2.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '7001:80'
    depends_on:
      - myapp-php-fpm

  myapp-php-fpm:
    image: php:7.2-fpm-buster
    build: php-fpm/
    # dockerfile: php-fpm/Dockerfile
    container_name: myapp-php-fpm
    volumes:
      - ../${CAKEPHP}:/var/www/myapp
      - ../${CAKEPHP2}:/var/www/myapp2
      - ./php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    depends_on:
      - myapp-mysql
      - myapp-mailhog

  myapp-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=myapp-mysql
      - MAX_EXECUTION_TIME=86400
      - UPLOAD_LIMIT=100M
      - PMA_USER=root
      - PMA_PASSWORD=123123
    depends_on:
      - myapp-mysql
    volumes:
      - ./phpmyadmin/config.inc.php:/var/www/html/config.inc.php

  myapp-mysql:
    image: mysql:5.7
    container_name: myapp-mysql
    volumes:
      - ../mysql:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ../sql:/home/sql
    ports:
      - '8106:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=123123
      - MYSQL_DATABASE=shop
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123123
    command: '--innodb_use_native_aio=0; --max_allowed_packet=32505856'

  myapp-mailhog:
    image: mailhog/mailhog:latest
    container_name: myapp-mailhog
    ports:
      - '1025:1025'
      - '8125:8025'
